### ISSUE TITLE
Return non-zero code on an error

### ISSUE THREAD

**Issue by NheelYolis** [InspectorMustache/base16-builder-python#16]
The program at the moment returns `0` even if an error has occurred. It would be useful to return a non-zero code on an error so it is possible to take any action in case of a failure.

For example, I have a script that uses `inject` to update configs and then reloads all corresponding programs. I would like to avoid reloading if the injection wasn't successful. At the moment, I'm just checking the output, which clearly isn't a good solution.

It also would be more correct if all error messages were written to `stderr`, not `stdout`.

**Comment by InspectorMustache** [comment]
Yes, good point!  I changed it so the builder reports warnings and errors to stderr and exits with 1 on fatal and 2 on non-fatal errors.  I haven't pushed this to PyPI yet so if you could give the master branch a try and see if it works for you, I would really appreciate it.

**Comment by NheelYolis** [comment]
The program indeed reports errors properly now!

Though if a target directory for the build output doesn't have execution permissions, code `2` is returned at the moment. I would consider it a fatal error?

**Comment by InspectorMustache** [comment]
Well, I guess that depends on your interpretation of fatal. This happens because the error is encountered in one of the co-routines that each build a single scheme.  So while the co-routines all fail, the program that is running them still finishes execution successfully. I guess, we could check whether all co-routines run into an issue and then treat that as a fatal error as opposed to only some of them failing. But then there would also have to be checks whether the problem is an error or just a warning. I don't think more complex error checking just to produce a more transparent exit code is really warranted in this case. I would recommend checking for file access permissions within your script instead.

**Comment by NheelYolis** [comment]
The thing is, if a directory doesn't have **write** permissions the program actually acts correctly. It prints *"No write permission for output directory."* and exits without even trying to build anything. I think it would make sense to act similarly if a directory doesn't have execution permissions for uniformity's sake.

**Comment by InspectorMustache** [comment]
Ooooookay then, so now it'll check for the write and execution bytes.  I wasn't aware execution rights were even necessary.  Anyway, you shouldn't really rely on these exit codes too much in your scripts since they are not explicit at all.

**Comment by NheelYolis** [comment]
Thanks! It returns `1` now if a directory lacks execution permissions, as expected.

Of course, I won't just rely on these codes and will perform other checks in my script if necessary. It's just a nice touch to have this (already great) program act correctly to missing execution permissions.

I appreciate the work you've done. I'm closing this issue now.
