### ISSUE TITLE
pybase16 update prompts for Github credentials

### ISSUE THREAD

**Issue by kevlar1818** [InspectorMustache/base16-builder-python#17]
Given: An empty current working directory and a clean pybase16-builder install (using pipx)

When: I run
```
$ pybase16 update
```

Then: I would expect no interaction is required. However, I get prompted for Github credentials:
```
$ pybase16 update
Creating sources.yaml…
Cloning sources…
Cloning templates…
Username for 'https://github.com':
```

**Comment by kevlar1818** [comment]
I think I found the issue and filed a PR in the master list:
https://github.com/chriskempson/base16-templates-source/pull/72

**Comment by InspectorMustache** [comment]
Eh, I don't know. This thing with the username prompt for non-existing repos seems to be related to Github. If you just try to clone any other url that doesn't exist, git will just give you an error message - as you would expect. That error message would then be passed to the builder which would print it to stderr. Of course, nearly all base16 repos are hosted on Github but I still think it's best to let the cloning process be handled by git. But if you know a git option that would cause it to just abort in these cases and return an error message then we could definitely add that as long as it doesn't interfere with anything else. Git turns off interactive use when stdin and stdout are not connected to a terminal but that's obviously not what we want for a command line application.

If you just enter bogus credentials, the builder will continue normally and just print the error message that is caused by that. Or, probably more elegantly, you can remove the offending repository from the list.yaml file and then run `update -c `.

**Comment by InspectorMustache** [comment]
> But if you know a git option that would cause it to just abort in these cases and return an error message then we could definitely add that as long as it doesn't interfere with anything else.

[This](https://serverfault.com/questions/544156/git-clone-fail-instead-of-prompting-for-credentials) looks promising. Should be easy to implement.

**Comment by kevlar1818** [comment]
@InspectorMustache Thanks! Just upgraded pybase16 and it works like a charm.
